force-app/main/default/objects/Case/fields/Activities_to_close__c.field-meta.xml
<CustomField>
    <fullName>Activities_to_close__c</fullName>
    <label>Activities to close</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Provider on-Hold</fullName>
            </value>
            <value>
                <fullName>Compile Audit Findings</fullName>
            </value>
            <value>
                <fullName>Confirm Credit Balance</fullName>
            </value>
            <value>
                <fullName>Contact Provider</fullName>
            </value>
            <value>
                <fullName>Dispose Case</fullName>
            </value>
            <value>
                <fullName>Identify Samples for Audit</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Perform Audit</fullName>
            </value>
            <value>
                <fullName>Perform Detailed Risk Assessment</fullName>
            </value>
            <value>
                <fullName>Perform Initial Risk Assessment</fullName>
            </value>
            <value>
                <fullName>Perform Provider &amp; Claims Data Research</fullName>
            </value>
            <value>
                <fullName>Perform Review</fullName>
            </value>
            <value>
                <fullName>Perform site Audit</fullName>
            </value>
            <value>
                <fullName>Prepare Addendum-A for Provider</fullName>
            </value>
            <value>
                <fullName>Receive &amp; Track Credit Balance</fullName>
            </value>
            <value>
                <fullName>Receive Document</fullName>
            </value>
            <value>
                <fullName>Request for Document</fullName>
            </value>
            <value>
                <fullName>Schedule Audit</fullName>
            </value>
            <value>
                <fullName>TBasic</fullName>
            </value>
            <value>
                <fullName>Test Activity 1</fullName>
            </value>
            <value>
                <fullName>Verify Provider Billing Issues</fullName>
            </value>
            <value>
                <fullName>Identify Samples &amp; Methodology for Audit</fullName>
            </value>
            <value>
                <fullName>Perform Provider Self Review</fullName>
            </value>
            <value>
                <fullName>Evaluate Provider Findings</fullName>
            </value>
            <value>
                <fullName>Perform DHSS PI Review/Audit</fullName>
            </value>
            <value>
                <fullName>Evaluate Audit Findings</fullName>
            </value>
            <value>
                <fullName>Determine Provider Actions</fullName>
            </value>
            <value>
                <fullName>Reconsideration</fullName>
            </value>
            <value>
                <fullName>Provider Appeal</fullName>
            </value>
            <value>
                <fullName>Recoupment/Financial Tracking</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Activities_to_enable__c.field-meta.xml
<CustomField>
    <fullName>Activities_to_enable__c</fullName>
    <label>Activities to enable</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Compile Audit Findings</fullName>
            </value>
            <value>
                <fullName>Confirm Credit Balance</fullName>
            </value>
            <value>
                <fullName>Contact Provider</fullName>
            </value>
            <value>
                <fullName>Dispose Case</fullName>
            </value>
            <value>
                <fullName>Identify Samples for Audit</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Perform Audit</fullName>
            </value>
            <value>
                <fullName>Perform Detailed Risk Assessment</fullName>
            </value>
            <value>
                <fullName>Perform Initial Risk Assessment</fullName>
            </value>
            <value>
                <fullName>Perform Provider &amp; Claims Data Research</fullName>
            </value>
            <value>
                <fullName>Perform Review</fullName>
            </value>
            <value>
                <fullName>Perform site Audit</fullName>
            </value>
            <value>
                <fullName>Prepare Addendum-A for Provider</fullName>
            </value>
            <value>
                <fullName>Provider on-Hold</fullName>
            </value>
            <value>
                <fullName>Receive &amp; Track Credit Balance</fullName>
            </value>
            <value>
                <fullName>Receive Document</fullName>
            </value>
            <value>
                <fullName>Request for Document</fullName>
            </value>
            <value>
                <fullName>Schedule Audit</fullName>
            </value>
            <value>
                <fullName>TBasic</fullName>
            </value>
            <value>
                <fullName>Test Activity 1</fullName>
            </value>
            <value>
                <fullName>Verify Provider Billing Issues</fullName>
            </value>
            <value>
                <fullName>Identify Samples &amp; Methodology for Audit</fullName>
            </value>
            <value>
                <fullName>Perform Provider Self Review</fullName>
            </value>
            <value>
                <fullName>Evaluate Provider Findings</fullName>
            </value>
            <value>
                <fullName>Perform DHSS PI Review/Audit</fullName>
            </value>
            <value>
                <fullName>Evaluate Audit Findings</fullName>
            </value>
            <value>
                <fullName>Determine Provider Actions</fullName>
            </value>
            <value>
                <fullName>Reconsideration</fullName>
            </value>
            <value>
                <fullName>Provider Appeal</fullName>
            </value>
            <value>
                <fullName>Recoupment/Financial Tracking</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Case_Name__c.field-meta.xml
<CustomField>
    <fullName>Case_Name__c</fullName>
    <label>Case Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/No_Of_Installment__c.field-meta.xml
<CustomField>
    <fullName>No_Of_Installment__c</fullName>
    <label>No Of Installment</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Case/fields/No_Of_Installment_Backup__c.field-meta.xml
<CustomField>
    <fullName>No_Of_Installment_Backup__c</fullName>
    <label>No Of Installment Backup</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Case/fields/Payment_Plan__c.field-meta.xml
<CustomField>
    <fullName>Payment_Plan__c</fullName>
    <label>Payment Plan</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/PP_Begin_Date__c.field-meta.xml
<CustomField>
    <fullName>PP_Begin_Date__c</fullName>
    <label>PP Begin Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/PP_Type__c.field-meta.xml
<CustomField>
    <fullName>PP_Type__c</fullName>
    <label>PP Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>One Time</fullName>
            </value>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Yearly</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/PP_Type_Backup__c.field-meta.xml
<CustomField>
    <fullName>PP_Type_Backup__c</fullName>
    <label>PP Type Backup</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Total_PP_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_PP_Amount__c</fullName>
    <label>Total PP Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Case/fields/Total_PP_Amount_Backup__c.field-meta.xml
<CustomField>
    <fullName>Total_PP_Amount_Backup__c</fullName>
    <label>Total PP Amount Backup</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Case_Activity__c/Case_Activity__c.object-meta.xml
<CustomObject>
    <label>Case Activity</label>
    <nameField>
        <label>Case Activity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Activities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Case_Activity__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Case Activities</relationshipLabel>
    <relationshipName>Case_Activities</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Case_Activity__c/fields/IsEnabled__c.field-meta.xml
<CustomField>
    <fullName>IsEnabled__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsEnabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case_Activity__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>In-Progress</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Plan_Detail__c/Payment_Plan_Detail__c.object-meta.xml
<CustomObject>
    <label>Payment Plan Detail</label>
    <nameField>
        <displayFormat>PPD-{0000000}</displayFormat>
        <label>Payment Plan No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Plan Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Plan_Detail__c/fields/Amount_to_Repaid__c.field-meta.xml
<CustomField>
    <fullName>Amount_to_Repaid__c</fullName>
    <label>Amount to Repay</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payment_Plan_Detail__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Payment Plan Details</relationshipLabel>
    <relationshipName>Payment_Plan_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Payment_Plan_Detail__c/fields/Installment__c.field-meta.xml
<CustomField>
    <fullName>Installment__c</fullName>
    <label>Installment #</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Payment_Plan_Detail__c/fields/Received_Amount__c.field-meta.xml
<CustomField>
    <fullName>Received_Amount__c</fullName>
    <label>Received Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payment_Plan_Detail__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yet to Pay</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Partially Paid</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PaymentPlanControllerTest.cls
@isTest
public with sharing class PaymentPlanControllerTest {
    @testSetup
    static void makeData(){
        Case csWeekly1 = new Case(
            Case_Name__c = 'Test Case 1',
            No_Of_Installment__c = 2,
            PP_Begin_Date__c = system.today(),
            Payment_Plan__c = 'Yes',
            PP_Type__c = 'Weekly',
            Total_PP_Amount__c = 15000
        );
        insert csWeekly1;

        Case csMonthly = new Case(
            Case_Name__c = 'Test Case 2',
            No_Of_Installment__c = 2,
            PP_Begin_Date__c = system.today(),
            Payment_Plan__c = 'Yes',
            PP_Type__c = 'Monthly',
            Total_PP_Amount__c = 15000
        );
        insert csMonthly;

        Case csOneTime = new Case(
            Case_Name__c = 'Test Case 3',
            No_Of_Installment__c = 2,
            PP_Begin_Date__c = system.today(),
            Payment_Plan__c = 'Yes',
            PP_Type__c = 'One Time',
            Total_PP_Amount__c = 15000
        );
        insert csOneTime;

        Case csWeekly2 = new Case(
            Case_Name__c = 'Test Case 4',
            No_Of_Installment__c = 2,
            PP_Begin_Date__c = system.today(),
            Payment_Plan__c = 'Yes',
            PP_Type__c = 'Weekly',
            Total_PP_Amount__c = 15000
        );
        insert csWeekly2;

        Case csUpdate = new Case(
            Case_Name__c = 'Test Case 5',
            No_Of_Installment__c = 2,
            PP_Begin_Date__c = system.today(),
            Payment_Plan__c = 'Yes',
            PP_Type__c = 'Yearly',
            Total_PP_Amount__c = 15000,
            No_Of_Installment_Backup__c = 1,
            Total_PP_Amount_Backup__c = 10000, 
            PP_Type_Backup__c = 'Monthly'
        );
        insert csUpdate;

        // Update Payment Plan Header in Case for test coverage
        Case csUpdateTrigger = new Case(
            Case_Name__c = 'Test Case 6',
            PP_Begin_Date__c = system.today(),
            Activities_to_close__c = 'Compile Audit Findings; Confirm Credit Balance',
            Activities_to_enable__c = 'Contact Provider'
        );
        insert csUpdateTrigger;

        Payment_Plan_Detail__c ppd = new Payment_Plan_Detail__c(
            Case__c = csWeekly1.Id,
            Amount_to_Repaid__c = 1500,
            Status__c = 'Paid',
            Payment_Due_Date__c = system.today().addMonths(1),
            Installment__c = 1,
            Received_Amount__c = 1500
        );
        insert ppd;

        String recordtypeId1 = Schema.SObjectType.Case_Activity__c.getRecordTypeInfosByName().get('Compile Audit Findings').getRecordTypeId();
        String recordtypeId2 = Schema.SObjectType.Case_Activity__c.getRecordTypeInfosByName().get('Confirm Credit Balance').getRecordTypeId();
        String recordtypeId3 = Schema.SObjectType.Case_Activity__c.getRecordTypeInfosByName().get('Contact Provider').getRecordTypeId();

        Case_Activity__c casact1 = new Case_Activity__c(
            RecordtypeId = recordtypeId1,
            Name = 'Compile Audit Findings',
            Case__c = csUpdateTrigger.id,
            IsEnabled__c = true
        );
        insert casact1;

        Case_Activity__c casact2 = new Case_Activity__c(
            RecordtypeId = recordtypeId2,
            Name = 'Confirm Credit Balance',
            Case__c = csUpdateTrigger.id,
            IsEnabled__c = true
        );
        insert casact2;
    }

    @isTest
    static void GetCaseAndPPDDetailsTest(){
        Case cs = [SELECT Id FROM Case WHERE Case_Name__c = 'Test Case 1'];
        PaymentPlanController.GetCaseAndPPDDetails(cs.Id);
    }

    @isTest
    static void PaymentPlanInitiationTest(){
        // Monthly
        Case caseRecMonthly = [SELECT Id, Payment_Plan__c, PP_Begin_Date__c, Total_PP_Amount__c, PP_Type__c, 
                            No_Of_Installment__c, No_Of_Installment_Backup__c, PP_Type_Backup__c, Total_PP_Amount_Backup__c     
                            FROM Case WHERE Case_Name__c = 'Test Case 2'];
        PaymentPlanController.PaymentPlanInitiation(JSON.serialize(caseRecMonthly));

        // One Time 
        Case caseRecOneTime = [SELECT Id, Payment_Plan__c, PP_Begin_Date__c, Total_PP_Amount__c, PP_Type__c, 
                            No_Of_Installment__c, No_Of_Installment_Backup__c, PP_Type_Backup__c, Total_PP_Amount_Backup__c     
                            FROM Case WHERE Case_Name__c = 'Test Case 3'];
        PaymentPlanController.PaymentPlanInitiation(JSON.serialize(caseRecOneTime));

        // Weekly
        Case caseRecWeekly = [SELECT Id, Payment_Plan__c, PP_Begin_Date__c, Total_PP_Amount__c, PP_Type__c, 
                            No_Of_Installment__c, No_Of_Installment_Backup__c, PP_Type_Backup__c, Total_PP_Amount_Backup__c     
                            FROM Case WHERE Case_Name__c = 'Test Case 4'];
        PaymentPlanController.PaymentPlanInitiation(JSON.serialize(caseRecWeekly));
    }

    @isTest
    static void updatePaymentPlanDetailsTest(){
        // Monthly
        Case caseRecUpdate = [SELECT Id, Payment_Plan__c, PP_Begin_Date__c, Total_PP_Amount__c, PP_Type__c, 
                            No_Of_Installment__c, No_Of_Installment_Backup__c, PP_Type_Backup__c, Total_PP_Amount_Backup__c     
                            FROM Case WHERE Case_Name__c = 'Test Case 5'];

        Map<String,String> parsedInputParams = new Map<String,String>{
            'totalPPAmtChange' => 'false',
            'PPTypeOrNoOfInstallmentChange' => 'true',
            'caseId' => caseRecUpdate.Id
        };

        PaymentPlanController.updatePaymentPlanDetails(JSON.serialize(parsedInputParams));

        Map<String,String> parsedInputParamstotalPPAmtChange = new Map<String,String>{
            'totalPPAmtChange' => 'true',
            'PPTypeOrNoOfInstallmentChange' => 'false',
            'caseId' => caseRecUpdate.Id
        };

        PaymentPlanController.updatePaymentPlanDetails(JSON.serialize(parsedInputParamstotalPPAmtChange));
    }

    @isTest
    static void updateCaseTriggerTest(){
        Case caseRecUpdate = [SELECT Id, Payment_Plan__c, PP_Begin_Date__c, Total_PP_Amount__c, PP_Type__c, 
                            No_Of_Installment__c, No_Of_Installment_Backup__c, PP_Type_Backup__c, Total_PP_Amount_Backup__c     
                            FROM Case WHERE Case_Name__c = 'Test Case 6'];

        caseRecUpdate.No_Of_Installment__c = 5;
        caseRecUpdate.PP_Type__c = 'Yearly';
        caseRecUpdate.Total_PP_Amount__c = 19000;
        caseRecUpdate.Payment_Plan__c = 'Yes';
        caseRecUpdate.Activities_to_close__c = 'Compile Audit Findings; Confirm Credit Balance; Contact Provider';
        caseRecUpdate.Activities_to_enable__c = 'Compile Audit Findings; Contact Provider';
        update caseRecUpdate;
    }
}