force-app/main/default/objects/Case/fields/Activities_to_close__c.field-meta.xml
<CustomField>
    <fullName>Activities_to_close__c</fullName>
    <label>Activities to close</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Provider on-Hold</fullName>
            </value>
            <value>
                <fullName>Compile Audit Findings</fullName>
            </value>
            <value>
                <fullName>Confirm Credit Balance</fullName>
            </value>
            <value>
                <fullName>Contact Provider</fullName>
            </value>
            <value>
                <fullName>Dispose Case</fullName>
            </value>
            <value>
                <fullName>Identify Samples for Audit</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Perform Audit</fullName>
            </value>
            <value>
                <fullName>Perform Detailed Risk Assessment</fullName>
            </value>
            <value>
                <fullName>Perform Initial Risk Assessment</fullName>
            </value>
            <value>
                <fullName>Perform Provider &amp; Claims Data Research</fullName>
            </value>
            <value>
                <fullName>Perform Review</fullName>
            </value>
            <value>
                <fullName>Perform site Audit</fullName>
            </value>
            <value>
                <fullName>Prepare Addendum-A for Provider</fullName>
            </value>
            <value>
                <fullName>Receive &amp; Track Credit Balance</fullName>
            </value>
            <value>
                <fullName>Receive Document</fullName>
            </value>
            <value>
                <fullName>Request for Document</fullName>
            </value>
            <value>
                <fullName>Schedule Audit</fullName>
            </value>
            <value>
                <fullName>TBasic</fullName>
            </value>
            <value>
                <fullName>Test Activity 1</fullName>
            </value>
            <value>
                <fullName>Verify Provider Billing Issues</fullName>
            </value>
            <value>
                <fullName>Identify Samples &amp; Methodology for Audit</fullName>
            </value>
            <value>
                <fullName>Perform Provider Self Review</fullName>
            </value>
            <value>
                <fullName>Evaluate Provider Findings</fullName>
            </value>
            <value>
                <fullName>Perform DHSS PI Review/Audit</fullName>
            </value>
            <value>
                <fullName>Evaluate Audit Findings</fullName>
            </value>
            <value>
                <fullName>Determine Provider Actions</fullName>
            </value>
            <value>
                <fullName>Reconsideration</fullName>
            </value>
            <value>
                <fullName>Provider Appeal</fullName>
            </value>
            <value>
                <fullName>Recoupment/Financial Tracking</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Activities_to_enable__c.field-meta.xml
<CustomField>
    <fullName>Activities_to_enable__c</fullName>
    <label>Activities to enable</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Compile Audit Findings</fullName>
            </value>
            <value>
                <fullName>Confirm Credit Balance</fullName>
            </value>
            <value>
                <fullName>Contact Provider</fullName>
            </value>
            <value>
                <fullName>Dispose Case</fullName>
            </value>
            <value>
                <fullName>Identify Samples for Audit</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Perform Audit</fullName>
            </value>
            <value>
                <fullName>Perform Detailed Risk Assessment</fullName>
            </value>
            <value>
                <fullName>Perform Initial Risk Assessment</fullName>
            </value>
            <value>
                <fullName>Perform Provider &amp; Claims Data Research</fullName>
            </value>
            <value>
                <fullName>Perform Review</fullName>
            </value>
            <value>
                <fullName>Perform site Audit</fullName>
            </value>
            <value>
                <fullName>Prepare Addendum-A for Provider</fullName>
            </value>
            <value>
                <fullName>Provider on-Hold</fullName>
            </value>
            <value>
                <fullName>Receive &amp; Track Credit Balance</fullName>
            </value>
            <value>
                <fullName>Receive Document</fullName>
            </value>
            <value>
                <fullName>Request for Document</fullName>
            </value>
            <value>
                <fullName>Schedule Audit</fullName>
            </value>
            <value>
                <fullName>TBasic</fullName>
            </value>
            <value>
                <fullName>Test Activity 1</fullName>
            </value>
            <value>
                <fullName>Verify Provider Billing Issues</fullName>
            </value>
            <value>
                <fullName>Identify Samples &amp; Methodology for Audit</fullName>
            </value>
            <value>
                <fullName>Perform Provider Self Review</fullName>
            </value>
            <value>
                <fullName>Evaluate Provider Findings</fullName>
            </value>
            <value>
                <fullName>Perform DHSS PI Review/Audit</fullName>
            </value>
            <value>
                <fullName>Evaluate Audit Findings</fullName>
            </value>
            <value>
                <fullName>Determine Provider Actions</fullName>
            </value>
            <value>
                <fullName>Reconsideration</fullName>
            </value>
            <value>
                <fullName>Provider Appeal</fullName>
            </value>
            <value>
                <fullName>Recoupment/Financial Tracking</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Case_Name__c.field-meta.xml
<CustomField>
    <fullName>Case_Name__c</fullName>
    <label>Case Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/No_Of_Installment__c.field-meta.xml
<CustomField>
    <fullName>No_Of_Installment__c</fullName>
    <label>No Of Installment</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Case/fields/Payment_Plan__c.field-meta.xml
<CustomField>
    <fullName>Payment_Plan__c</fullName>
    <label>Payment Plan</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/PP_Begin_Date__c.field-meta.xml
<CustomField>
    <fullName>PP_Begin_Date__c</fullName>
    <label>PP Begin Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/PP_Type__c.field-meta.xml
<CustomField>
    <fullName>PP_Type__c</fullName>
    <label>PP Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>One Time</fullName>
            </value>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Yearly</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Total_PP_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_PP_Amount__c</fullName>
    <label>Total PP Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Case_Activity__c/Case_Activity__c.object-meta.xml
<CustomObject>
    <label>Case Activity</label>
    <nameField>
        <label>Case Activity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Activities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Case_Activity__c/fields/Activity_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Activity_Start_Date__c</fullName>
    <label>Activity Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case_Activity__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Case Activities</relationshipLabel>
    <relationshipName>Case_Activities</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Case_Activity__c/fields/Case_Activity_Type__c.field-meta.xml
<CustomField>
    <fullName>Case_Activity_Type__c</fullName>
    <label>Case Activity Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Compile Audit Findings</fullName>
            </value>
            <value>
                <fullName>Confirm Credit Balance</fullName>
            </value>
            <value>
                <fullName>Contact Provider</fullName>
            </value>
            <value>
                <fullName>Dispose Case</fullName>
            </value>
            <value>
                <fullName>Identify Samples for Audit</fullName>
            </value>
            <value>
                <fullName>Perform Audit</fullName>
            </value>
            <value>
                <fullName>Perform Detailed Risk Assessment</fullName>
            </value>
            <value>
                <fullName>Perform Initial Risk Assessment</fullName>
            </value>
            <value>
                <fullName>Perform Provider &amp; Claims data research</fullName>
            </value>
            <value>
                <fullName>Perform Review</fullName>
            </value>
            <value>
                <fullName>Prepare Addendum – A for Provider</fullName>
            </value>
            <value>
                <fullName>Receive and Track Credit Balance</fullName>
            </value>
            <value>
                <fullName>Receive Document</fullName>
            </value>
            <value>
                <fullName>Request for Document (Addendum-A)</fullName>
            </value>
            <value>
                <fullName>Schedule Audit</fullName>
            </value>
            <value>
                <fullName>Send Demand Letter</fullName>
            </value>
            <value>
                <fullName>Verify Provider Billing Issues</fullName>
            </value>
            <value>
                <fullName>Perform Site Audit</fullName>
            </value>
            <value>
                <fullName>Provider on-Hold</fullName>
            </value>
            <value>
                <fullName>Test Activity 1</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case_Activity__c/fields/IsEnabled__c.field-meta.xml
<CustomField>
    <fullName>IsEnabled__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsEnabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/CaseTriggerTest.cls
@IsTest    
Public Class CaseTriggerTest{

    public Static testMethod void CaseTriggerTest(){    
        Id accRectypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Billing Provider').getRecordTypeId();

        Account acc = new Account(
            LastName = 'Test',
            FirstName = 'Test',
            RecordTypeId = accRectypeId,
            BillingStreet = 'Street', BillingPostalCode = '123', 
            BillingCity = 'chennai', BillingCountry = 'india'
        );
        insert acc;

        ApexPages.StandardController sc = new ApexPages.StandardController(acc);
        CaseAssociationsController testAccPlan = new CaseAssociationsController(sc);

        Case csMonthly0 = new Case(
            Case_Name__c = 'Test Case 1',
            No_Of_Installment__c = 2,
            PP_Begin_Date__c = system.today(),
            Payment_Plan__c = 'Yes',
            PP_Type__c = 'Monthly',
            Total_PP_Amount__c = 15000,
            accountId = acc.Id
        );
        insert csMonthly0;

        Case csMonthly1 = new Case(
            Case_Name__c = 'Test Case 1',
            PP_Begin_Date__c = system.today(),
            Payment_Plan__c = 'No',
            PP_Type__c = 'Monthly',
            Total_PP_Amount__c = 15000
        );
        insert csMonthly1;

        Case_Activity__c ca1 = new Case_Activity__c(
            Name = 'Perform Provider Self Review',
            Case__c = csMonthly1.Id,
            Activity_Start_Date__c = system.today(),
            IsEnabled__c = true,
            Case_Activity_Type__c = 'Perform Provider Self Review'
        );
        insert ca1;

        Case_Activity__c ca2 = new Case_Activity__c(
            Name = 'Evaluate Provider Findings',
            Case__c = csMonthly1.Id,
            Activity_Start_Date__c = system.today(),
            IsEnabled__c = false,
            Case_Activity_Type__c = 'Evaluate Provider Findings'
        );
        insert ca2;

        Case csMonthly2 = new Case(
            Id = csMonthly1.Id,
            Case_Name__c = 'Test Case 2',
            No_Of_Installment__c = 2,
            PP_Begin_Date__c = system.today(),
            Payment_Plan__c = 'Yes',
            PP_Type__c = 'Monthly',
            Total_PP_Amount__c = 15000,
            Activities_to_close__c = 'Perform Provider Self Review',
            Activities_to_enable__c = 'Evaluate Provider Findings'
        );
        update csMonthly2;
    }
}