force-app/main/default/objects/Case/fields/Case_Name__c.field-meta.xml
<CustomField>
    <fullName>Case_Name__c</fullName>
    <label>Case Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case_Activity__c/Case_Activity__c.object-meta.xml
<CustomObject>
    <label>Case Activity</label>
    <nameField>
        <label>Case Activity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Activities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Case_Activity__c/fields/Activity_Business_Status__c.field-meta.xml
<CustomField>
    <fullName>Activity_Business_Status__c</fullName>
    <label>Activity Business Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Administrative Action</fullName>
            </value>
            <value>
                <fullName>Audit Completed</fullName>
            </value>
            <value>
                <fullName>Audit Findings Documented</fullName>
            </value>
            <value>
                <fullName>Audit Findings In Progress</fullName>
            </value>
            <value>
                <fullName>Audit Not Performed</fullName>
            </value>
            <value>
                <fullName>Audit Scheduled</fullName>
            </value>
            <value>
                <fullName>Case Referral – Administrative Action</fullName>
            </value>
            <value>
                <fullName>Case Referral – Credit Balance</fullName>
            </value>
            <value>
                <fullName>Case Referral – Provider Audit</fullName>
            </value>
            <value>
                <fullName>Case Referral - Recovery</fullName>
                <label>Case Referral – Recovery</label>
            </value>
            <value>
                <fullName>Close Case</fullName>
            </value>
            <value>
                <fullName>Contact Successful</fullName>
            </value>
            <value>
                <fullName>Contact Unsuccessful</fullName>
            </value>
            <value>
                <fullName>Credit Balance Not Verified</fullName>
            </value>
            <value>
                <fullName>Credit Balance Reported</fullName>
            </value>
            <value>
                <fullName>Credit Balance Verified</fullName>
            </value>
            <value>
                <fullName>Credit Balance Worksheet Review</fullName>
            </value>
            <value>
                <fullName>Detailed Risk Score – High</fullName>
            </value>
            <value>
                <fullName>Detailed Risk Score – Low</fullName>
            </value>
            <value>
                <fullName>Detailed Risk Score – Medium</fullName>
            </value>
            <value>
                <fullName>Detailed Risk Score – Not Determined</fullName>
            </value>
            <value>
                <fullName>Document Attempt Unsuccessful</fullName>
            </value>
            <value>
                <fullName>Document Incomplete</fullName>
            </value>
            <value>
                <fullName>Document In Progress</fullName>
            </value>
            <value>
                <fullName>Document Not Received</fullName>
            </value>
            <value>
                <fullName>Document Prepared</fullName>
            </value>
            <value>
                <fullName>Document Received</fullName>
            </value>
            <value>
                <fullName>Document Request Completed</fullName>
            </value>
            <value>
                <fullName>Document Request Verified</fullName>
            </value>
            <value>
                <fullName>Document Verified</fullName>
            </value>
            <value>
                <fullName>Activity Not Applicable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case_Activity__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Case Activities</relationshipLabel>
    <relationshipName>Case_Activities</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Case_Activity__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>In-Progress</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/OI_BusinessStatusANDStatusUpdate.cls
@IsTest
public class OI_BusinessStatusANDStatusUpdate {
    
    Public Static testmethod void Test_OI_BusinessStatusANDStatusUpdate(){
        
        Case cas = New Case();
        cas.Case_Name__c = 'Test Case';        
        Insert cas;
        //String strRecordTypeId = [Select Id From RecordType Where SobjectType = 'Case_Activity__c ' and Name = 'Receive Document'].Id;
        Id RecordTypeId = Schema.SObjectType.Case_Activity__c.getRecordTypeInfosByName().get('Receive & Track Credit Balance').getRecordTypeId();
        
        Case_Activity__c casAct = New Case_Activity__c();
        casAct.Case__c = cas.Id;
        casAct.Activity_Business_Status__c = 'Credit Balance Reported';
        casAct.RecordTypeId = RecordTypeId ;
        Insert casAct;
        casAct.Activity_Business_Status__c = 'Activity Not Applicable';
        casAct.Status__c = 'Completed';
        Update casAct;
        
        Case cas1 = New Case();
        cas1.Case_Name__c = 'Test Case';   
        cas1.Type = 'Provider Audit - Onsite';
        Insert cas1;        
        
    }
    
    
}