force-app/main/default/objects/Case/fields/Case_Name__c.field-meta.xml
<CustomField>
    <fullName>Case_Name__c</fullName>
    <label>Case Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/No_Of_Installment__c.field-meta.xml
<CustomField>
    <fullName>No_Of_Installment__c</fullName>
    <label>No Of Installment</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Case/fields/Payment_Plan__c.field-meta.xml
<CustomField>
    <fullName>Payment_Plan__c</fullName>
    <label>Payment Plan</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/PP_Begin_Date__c.field-meta.xml
<CustomField>
    <fullName>PP_Begin_Date__c</fullName>
    <label>PP Begin Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/PP_Type__c.field-meta.xml
<CustomField>
    <fullName>PP_Type__c</fullName>
    <label>PP Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>One Time</fullName>
            </value>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Yearly</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Total_Overpayment__c.field-meta.xml
<CustomField>
    <fullName>Total_Overpayment__c</fullName>
    <label>Total Overpayment</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Case/fields/Total_PP_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_PP_Amount__c</fullName>
    <label>Total PP Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Collo_Codes__c/Collo_Codes__c.object-meta.xml
<CustomObject>
    <label>Collo Code</label>
    <nameField>
        <label>Collo Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Collo Codes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Collo_Codes__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Collo Codes</relationshipLabel>
    <relationshipName>Collo_Codes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ColloCodeTriggerTest.cls
@isTest
public with sharing class ColloCodeTriggerTest {
    @isTest
    static void ColloCodeAmountExceedOverPayment(){
        Id recordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Medicaid PI Audit').getRecordTypeId();

        Case csWeekly1 = new Case(
            Case_Name__c = 'Test Case 1',
            No_Of_Installment__c = 2,
            PP_Begin_Date__c = system.today(),
            Payment_Plan__c = 'Yes',
            PP_Type__c = 'Weekly',
            Total_PP_Amount__c = 15000,
            Total_Overpayment__c = 20,
            RecordTypeId = recordTypeId 
        );
        insert csWeekly1;

        Collo_Codes__c cc1 = new Collo_Codes__c(
            Name = 'CC1',
            Amount__c = 21,
            Case__c = csWeekly1.Id
        );
        Insert cc1;
    }

    @isTest
    static void ZeroOverPayment(){
        Id recordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Medicaid PI Audit').getRecordTypeId();

        Case csWeekly2 = new Case(
            Case_Name__c = 'Test Case 1',
            No_Of_Installment__c = 2,
            PP_Begin_Date__c = system.today(),
            Payment_Plan__c = 'Yes',
            PP_Type__c = 'Weekly',
            Total_PP_Amount__c = 15000,
            Total_Overpayment__c = 0,
            RecordTypeId = recordTypeId 
        );
        insert csWeekly2;

        Collo_Codes__c cc2 = new Collo_Codes__c(
            Name = 'CC2',
            Amount__c = 21,
            Case__c = csWeekly2.Id
        );
        Insert cc2;
    }

    @isTest
    static void AggregateValue(){
        Id recordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Medicaid PI Audit').getRecordTypeId();

        Case csWeekly2 = new Case(
            Case_Name__c = 'Test Case 1',
            No_Of_Installment__c = 2,
            PP_Begin_Date__c = system.today(),
            Payment_Plan__c = 'Yes',
            PP_Type__c = 'Weekly',
            Total_PP_Amount__c = 15000,
            Total_Overpayment__c = 30,
            RecordTypeId = recordTypeId 
        );
        insert csWeekly2;

        Collo_Codes__c cc2 = new Collo_Codes__c(
            Name = 'CC2',
            Amount__c = 15,
            Case__c = csWeekly2.Id
        );
        Insert cc2;

        Collo_Codes__c cc3 = new Collo_Codes__c(
            Name = 'CC2',
            Amount__c = 16,
            Case__c = csWeekly2.Id
        );
        Insert cc3;
    }

    @isTest
    static void MorethanSixColloCode(){
        Id recordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Medicaid PI Audit').getRecordTypeId();

        Case csWeekly2 = new Case(
            Case_Name__c = 'Test Case 1',
            No_Of_Installment__c = 2,
            PP_Begin_Date__c = system.today(),
            Payment_Plan__c = 'Yes',
            PP_Type__c = 'Weekly',
            Total_PP_Amount__c = 15000,
            Total_Overpayment__c = 10,
            RecordTypeId = recordTypeId 
        );
        insert csWeekly2;

        List<Collo_Codes__c> ccList = new List<Collo_Codes__c>();

        for(Integer i = 1; i <= 6; i++){
            Collo_Codes__c cc2 = new Collo_Codes__c(
                Name = 'CC2',
                Amount__c = 1,
                Case__c = csWeekly2.Id
            );
            ccList.add(cc2);
        }

        if(ccList.size() > 0){
            insert ccList;
        }

        Collo_Codes__c cc2 = new Collo_Codes__c(
            Name = 'CC2',
            Amount__c = 1,
            Case__c = csWeekly2.Id
        );
        Insert cc2;

        /*Collo_Codes__c cc3 = new Collo_Codes__c(
            Name = 'CC2',
            Amount__c = 16,
            Case__c = csWeekly2.Id
        );
        Insert cc3;*/
    }
}