force-app/main/default/objects/Case/fields/Case_Name__c.field-meta.xml
<CustomField>
    <fullName>Case_Name__c</fullName>
    <label>Case Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case_Associate__c/Case_Associate__c.object-meta.xml
<CustomObject>
    <label>Case Association</label>
    <nameField>
        <displayFormat>{000}</displayFormat>
        <label>Case Associate No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Associations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Case_Associate__c/fields/Associate_Type__c.field-meta.xml
<CustomField>
    <fullName>Associate_Type__c</fullName>
    <label>Associate Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Primary</fullName>
            </value>
            <value>
                <fullName>Secondary</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case_Associate__c/fields/Case_Number__c.field-meta.xml
<CustomField>
    <fullName>Case_Number__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case Number</label>
    <referenceTo>Case</referenceTo>
    <relationshipName>Case_Associates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case_Associate__c/fields/Entity1__c.field-meta.xml
<CustomField>
    <fullName>Entity1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Entity</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Entity_Type__c</field>
            <operation>equals</operation>
            <valueField>Account.Entity_Type__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipName>Case_Associates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case_Associate__c/fields/Entity_Type__c.field-meta.xml
<CustomField>
    <fullName>Entity_Type__c</fullName>
    <label>Case Associate</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Provider</fullName>
            </value>
            <value>
                <fullName>Member</fullName>
            </value>
            <value>
                <fullName>Claims</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case_Associate__c/recordTypes/Other.recordType-meta.xml
<RecordType>
    <fullName>Other</fullName>
    <active>true</active>
    <label>Other</label>
</RecordType>

force-app/main/default/objects/Case_Associate__c/recordTypes/Provider.recordType-meta.xml
<RecordType>
    <fullName>Provider</fullName>
    <active>true</active>
    <label>Provider</label>
</RecordType>

force-app/main/default/classes/OI_PrimaryAssociateType_Test.cls
@ISTest
public class OI_PrimaryAssociateType_Test {
    
    
    
    Public Static testMethod void PrimaryAssociateTypeTest(){
        
        Contact con = New Contact();
        con.LastName = 'Test name';
        insert con;
        
        Case cs = New Case();
        cs.Case_Name__c = 'Test Case';
        cs.Status = 'Completed';
        cs.Origin = 'Referral';
        cs.Type = 'Client Audit';
        insert Cs;
        
        Case_Associate__c ca = New Case_Associate__c();
        // ca.name = 'test Name';
        ca.Case_Number__c = Cs.Id;
        ca.Associate_Type__c = 'Secondary';
        ca.Entity_Type__c = 'Billing Provider';
        boolean b = false;
        for(Apexpages.Message thisMsg : ApexPages.getMessages()){
            system.assert(thisMsg.getDetail().contains('Primary Associate Type was Already Created. So Please Choose "Secondary" or "Other" '));
        }
        insert ca;
        //ca.Associate_Type__c = 'Primary';
        //update ca;
        Map<Id,Case_Associate__c> casMap  = New Map<Id,Case_Associate__c>();
        set<Id> caseId1 = New Set<Id>();
        Map<Id,Case_Associate__c> accMap = New Map<Id,Case_Associate__c>();
        Case_Associate__c ca2 = New Case_Associate__c();
        ca2.Case_Number__c = cs.Id;
        ca2.Entity_Type__c = 'Billing Provider';
        ca2.Associate_Type__c = 'Primary';
        //accMap.put(ca2.Entity1__c,ca2);
        //caseId1.add(ca2.Case_Number__c);
        //casMap.put(ca2.Case_Number__c,ca2);
        insert ca2;
        
        
        cs.ContactId = con.Id;
        update cs;
    }
    
}