force-app/main/default/objects/Case/fields/Case_Name__c.field-meta.xml
<CustomField>
    <fullName>Case_Name__c</fullName>
    <label>Case Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case_Activity__c/Case_Activity__c.object-meta.xml
<CustomObject>
    <label>Case Activity</label>
    <nameField>
        <label>Case Activity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Activities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Case_Activity__c/fields/Activity_Business_Status__c.field-meta.xml
<CustomField>
    <fullName>Activity_Business_Status__c</fullName>
    <label>Activity Business Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Administrative Action</fullName>
            </value>
            <value>
                <fullName>Audit Completed</fullName>
            </value>
            <value>
                <fullName>Audit Findings Documented</fullName>
            </value>
            <value>
                <fullName>Audit Findings In Progress</fullName>
            </value>
            <value>
                <fullName>Audit Not Performed</fullName>
            </value>
            <value>
                <fullName>Audit Scheduled</fullName>
            </value>
            <value>
                <fullName>Case Referral – Administrative Action</fullName>
            </value>
            <value>
                <fullName>Case Referral – Credit Balance</fullName>
            </value>
            <value>
                <fullName>Case Referral – Provider Audit</fullName>
            </value>
            <value>
                <fullName>Case Referral - Recovery</fullName>
                <label>Case Referral – Recovery</label>
            </value>
            <value>
                <fullName>Close Case</fullName>
            </value>
            <value>
                <fullName>Contact Successful</fullName>
            </value>
            <value>
                <fullName>Contact Unsuccessful</fullName>
            </value>
            <value>
                <fullName>Credit Balance Not Verified</fullName>
            </value>
            <value>
                <fullName>Credit Balance Reported</fullName>
            </value>
            <value>
                <fullName>Credit Balance Verified</fullName>
            </value>
            <value>
                <fullName>Credit Balance Worksheet Review</fullName>
            </value>
            <value>
                <fullName>Detailed Risk Score – High</fullName>
            </value>
            <value>
                <fullName>Detailed Risk Score – Low</fullName>
            </value>
            <value>
                <fullName>Detailed Risk Score – Medium</fullName>
            </value>
            <value>
                <fullName>Detailed Risk Score – Not Determined</fullName>
            </value>
            <value>
                <fullName>Document Attempt Unsuccessful</fullName>
            </value>
            <value>
                <fullName>Document Incomplete</fullName>
            </value>
            <value>
                <fullName>Document In Progress</fullName>
            </value>
            <value>
                <fullName>Document Not Received</fullName>
            </value>
            <value>
                <fullName>Document Prepared</fullName>
            </value>
            <value>
                <fullName>Document Received</fullName>
            </value>
            <value>
                <fullName>Document Request Completed</fullName>
            </value>
            <value>
                <fullName>Document Request Verified</fullName>
            </value>
            <value>
                <fullName>Document Verified</fullName>
            </value>
            <value>
                <fullName>Initial Risk Score – Low</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case_Activity__c/fields/Activity_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Activity_End_Date__c</fullName>
    <label>Activity End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case_Activity__c/fields/Activity_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Activity_Start_Date__c</fullName>
    <label>Activity Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case_Activity__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Case Activities</relationshipLabel>
    <relationshipName>Case_Activities</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Case_Activity__c/fields/Case_Activity_Type__c.field-meta.xml
<CustomField>
    <fullName>Case_Activity_Type__c</fullName>
    <label>Case Activity Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Compile Audit Findings</fullName>
            </value>
            <value>
                <fullName>Confirm Credit Balance</fullName>
            </value>
            <value>
                <fullName>Contact Provider</fullName>
            </value>
            <value>
                <fullName>Dispose Case</fullName>
            </value>
            <value>
                <fullName>Identify Samples for Audit</fullName>
            </value>
            <value>
                <fullName>Perform Audit</fullName>
            </value>
            <value>
                <fullName>Perform Detailed Risk Assessment</fullName>
            </value>
            <value>
                <fullName>Perform Initial Risk Assessment</fullName>
            </value>
            <value>
                <fullName>Perform Provider &amp; Claims data research</fullName>
            </value>
            <value>
                <fullName>Perform Review</fullName>
            </value>
            <value>
                <fullName>Prepare Addendum – A for Provider</fullName>
            </value>
            <value>
                <fullName>Receive and Track Credit Balance</fullName>
            </value>
            <value>
                <fullName>Receive Document</fullName>
            </value>
            <value>
                <fullName>Request for Document (Addendum-A)</fullName>
            </value>
            <value>
                <fullName>Schedule Audit</fullName>
            </value>
            <value>
                <fullName>Send Demand Letter</fullName>
            </value>
            <value>
                <fullName>Verify Provider Billing Issues</fullName>
            </value>
            <value>
                <fullName>Perform Site Audit</fullName>
            </value>
            <value>
                <fullName>Provider on-Hold</fullName>
            </value>
            <value>
                <fullName>Test Activity 1</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case_Activity__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>In-Progress</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestTriggerCaseActivity.cls
@IsTest    
Public class TestTriggerCaseActivity {

    public Static testMethod void CaseAssociate(){
    
    //insert Case//
    Case case1 = new Case(Case_Name__c='TestCase1', Type='Provider Audit-Onsite', Status='Initated', Priority='P1',  Origin='Data Mining');
    insert case1;
    
    Case_Activity__c ca1 = new Case_Activity__c(Case_Activity_Type__c='Schedule Audit', Name='Schedule Audit', Status__c='Not Started', Case__c=case1.Id);
    insert ca1;
    
    ca1.Activity_Start_Date__c = system.today();
    ca1.Activity_End_Date__c = system.today()+1;
    update ca1; 
    
    List<Case_Activity__c> lstCaseActi = new List<Case_Activity__c>();
    Case_Activity__c objca;
    
    objca = new Case_Activity__c(Case__c = case1.id, Case_Activity_Type__c='Perform Provider & Claims Data Research', Name='1:Perform Provider & Claims Data Research', Status__c='Not Started');
    lstCaseActi.add(objca);
    objca = new Case_Activity__c(Case__c = case1.id, Case_Activity_Type__c='Perform Initial Risk Assessment', Name='2:Perform Initial Risk Assessment', Status__c='Not Started');
    lstCaseActi.add(objca);
    objca = new Case_Activity__c(Case__c = case1.id, Case_Activity_Type__c='Perform Detailed Risk Assessment', Name='3:Perform Detailed Risk Assessment', Status__c='Not Started');
    lstCaseActi.add(objca);
    objca= new Case_Activity__c(Case__c = case1.id, Case_Activity_Type__c='Identify Samples for Audit', Name='4:Identify Samples for Audit', Status__c='Not Started');
    lstCaseActi.add(objca);
    objca = new Case_Activity__c(Case__c = case1.id, Case_Activity_Type__c='Schedule Audit', Name='5:Schedule Audit', Status__c='Not Started');
    lstCaseActi.add(objca);
    objca = new Case_Activity__c(Case__c = case1.id, Case_Activity_Type__c='Perform Audit', Name='6:Perform Audit', Status__c='Not Started');
    lstCaseActi.add(objca);
    objca = new Case_Activity__c(Case__c = case1.id, Case_Activity_Type__c='Compile Audit Findings', Name='7:Compile Audit Findings', Status__c='Not Started');
    lstCaseActi.add(objca);
    
    insert lstCaseActi;
    
    Test.StartTest();
    for(Case_Activity__c irow: lstCaseActi)
    {    
        if(irow.Case_Activity_Type__c =='Perform Initial Risk Assessment'){
            irow.Activity_Business_Status__c = 'Initial Risk Score – Low';
            
        }
        //update irow;
    }   
    Test.StopTest(); 
    }

}