force-app/main/default/objects/Case/fields/Case_Name__c.field-meta.xml
<CustomField>
    <fullName>Case_Name__c</fullName>
    <label>Case Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case_Activity__c/Case_Activity__c.object-meta.xml
<CustomObject>
    <label>Case Activity</label>
    <nameField>
        <label>Case Activity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Activities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Case_Activity__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Case Activities</relationshipLabel>
    <relationshipName>Case_Activities</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/CaseActivity_SK_Test.cls
@isTest
public class CaseActivity_SK_Test{
    
    public testmethod static Case_Activity__c CaseActCreation(){
        case cas = new Case();
        cas.Case_Name__c = 'Provider Audit';
        cas.Type = 'Provider Audit-Onsite';
        cas.Status = 'In-Progress';
        insert cas;
        
        String recordtypeId = Schema.SObjectType.Case_Activity__c.getRecordTypeInfosByName().get('Contact Provider').getRecordTypeId();
        Case_Activity__c casact = new Case_Activity__c();
        casact.RecordtypeId = recordtypeId;
        casact.Name = 'Provider Audit';
        casact.Case__c = cas.id;
        insert casact;
        
        return casact;
    }
    
    private testmethod static void positiveTest(){
        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse();       
        Case_Activity__c cas = CaseActCreation();
        Case_Activity__c caseact1 = [select id from Case_Activity__c where id =: cas.id];
        req.requestURI = '/services/apexrest/CaseActivityDetails/';  
        req.httpMethod = 'POST';
        req.addHeader('Content-Type','application/json');
        String bodyStr='{"caseActId":"'+ caseact1.Id + '"}';
        
        req.Requestbody=Blob.ValueOf(bodyStr);
        RestContext.request = req;
        RestContext.response = res;
        
        Test.startTest();
        CaseActivity_SK.CaseActivityDetails();
        Test.stopTest();       
    }
    
    private testmethod static void negativeTest_1(){
        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse();       
        Case_Activity__c cas = CaseActCreation();
        Case_Activity__c caseact1 = [select id from Case_Activity__c where id =: cas.id];
        req.requestURI = '/services/apexrest/CaseActivityDetails/';  
        req.httpMethod = 'POST';
        req.addHeader('Content-Type','application/json');
        String bodyStr='{"caseActId":"'+ caseact1.id+ '"}';
        
        req.Requestbody=Blob.ValueOf(bodyStr);
        RestContext.request = req;
        RestContext.response = res;
        
        Test.startTest();
        CaseActivity_SK.CaseActivityDetails();
        Test.stopTest();       
    }
    
    private testmethod static void negativeTest_2(){
        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse();       
        Case_Activity__c cas = CaseActCreation();
        Case_Activity__c caseact1 = [select id from Case_Activity__c where id =: cas.id];
        req.requestURI = '/services/apexrest/CaseActivityDetails/';  
        req.httpMethod = 'POST';
        //req.addHeader('Content-Type','application/json');
        String bodyStr='{"caseActId":"'+ caseact1.id+ '"}';
        
        req.Requestbody=Blob.ValueOf(bodyStr);
        RestContext.request = req;
        RestContext.response = res;
        
        Test.startTest();
        CaseActivity_SK.CaseActivityDetails();
        Test.stopTest();       
    }
    
    private testmethod static void negativeTest_3(){
        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse();       
        Case_Activity__c cas = CaseActCreation();
        Case_Activity__c caseact1 = [select id from Case_Activity__c where id =: cas.id];
        //req.requestURI = '/services/apexrest/CaseAndActivityDetails/';  
        //req.httpMethod = 'POST';
        //req.addHeader('Content-Type','application/json');
        String bodyStr='{"caseActId":"'+ caseact1.id+ '"}';
        
        req.Requestbody=Blob.ValueOf(bodyStr);
        //RestContext.request = req;
        RestContext.response = res;
        
        Test.startTest();
        CaseActivity_SK.CaseActivityDetails();
        Test.stopTest();       
    }
    
    private testmethod static void negativeTest_4(){
        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse();       
        Case_Activity__c cas = CaseActCreation();
        Case_Activity__c caseact1 = [select id from Case_Activity__c where id =: cas.id];
        req.requestURI = '/services/apexrest/CaseActivityDetails/';  
        req.httpMethod = 'POST';
        req.addHeader('Content-Type','application/json');
        String bodyStr='{"caseActId":"'+ caseact1.id+ '"}';
        
        //req.Requestbody=Blob.ValueOf(bodyStr);
        RestContext.request = req;
        RestContext.response = res;
        
        Test.startTest();
        CaseActivity_SK.CaseActivityDetails();
        Test.stopTest();       
    }
}