force-app/main/default/objects/Case/fields/Review_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Review_Start_Date__c</fullName>
    <label>Review Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <label>Source</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AS 47.05.200 (Contracted Audit)</fullName>
            </value>
            <value>
                <fullName>Analytic/Outlier</fullName>
            </value>
            <value>
                <fullName>Other Complaint/Referral</fullName>
            </value>
            <value>
                <fullName>Division of Healthcare Services Referral</fullName>
            </value>
            <value>
                <fullName>enior and Disabilities Services Division Referral</fullName>
            </value>
            <value>
                <fullName>Behavioral Health Services Division</fullName>
            </value>
            <value>
                <fullName>Medicaid Fraud Control Unit</fullName>
            </value>
            <value>
                <fullName>Medicaid Fraud Control Unit - Global Settlement</fullName>
            </value>
            <value>
                <fullName>Payment Error Rate Measurement (PERM)</fullName>
            </value>
            <value>
                <fullName>Universal Program Integrity Contractor (UPIC)</fullName>
            </value>
            <value>
                <fullName>Self-Audit - Legislative -7 AAC 160.115(b)</fullName>
            </value>
            <value>
                <fullName>Self-Audit - Program Integrity Initiated</fullName>
            </value>
            <value>
                <fullName>Self-Disclosure - Provider Initiated</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case_Associate__c/Case_Associate__c.object-meta.xml
<CustomObject>
    <label>Case Association</label>
    <nameField>
        <displayFormat>{000}</displayFormat>
        <label>Case Associate No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Associations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Case_Associate__c/fields/Associate_Type__c.field-meta.xml
<CustomField>
    <fullName>Associate_Type__c</fullName>
    <label>Associate Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Primary</fullName>
            </value>
            <value>
                <fullName>Secondary</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case_Associate__c/fields/Case_Number__c.field-meta.xml
<CustomField>
    <fullName>Case_Number__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case Number</label>
    <referenceTo>Case</referenceTo>
    <relationshipName>Case_Associates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case_Associate__c/fields/Entity1__c.field-meta.xml
<CustomField>
    <fullName>Entity1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Entity</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Entity_Type__c</field>
            <operation>equals</operation>
            <valueField>Account.Entity_Type__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipName>Case_Associates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/associatedCaseList.cls
public with sharing class associatedCaseList {
    @AuraEnabled
    public static string fetchCaseListAssociated(String caseRecordId){
        List<Case_Associate__c> lstOfCaseAssociate = new List<Case_Associate__c>();
        Map<String, Object> outputMap = new Map<String, Object>();

        try {
            list<string> entityIds = new list<string>();
            for(Case_Associate__c caseAssociate : [SELECT Id, Entity1__c 
                FROM Case_Associate__c 
                WHERE Case_Number__c =: caseRecordId]){
                    entityIds.add(caseAssociate.Entity1__c);
            }

            System.debug('entityIds '+ entityIds);

            if(entityIds.size() > 0){
                for(Case_Associate__c caseAssociate : [SELECT Id, Entity1__r.Id,
                    Entity1__r.Name, Case_Number__r.Id,
                    Case_Number__r.Type, Case_Number__r.CaseNumber, 
                    Case_Number__r.Source__c, Case_Number__r.Origin, 
                    Case_Number__r.Review_Start_Date__c, Case_Number__r.Status, 
                    Case_Number__r.Description, Case_Number__r.Priority, Associate_Type__c 
                    FROM Case_Associate__c 
                    WHERE Entity1__c IN: entityIds
                    AND Case_Number__c <>: caseRecordId]){
                        lstOfCaseAssociate.add(caseAssociate);
                }
            }

            System.debug('lstOfCaseAssociate '+ lstOfCaseAssociate);

            if(lstOfCaseAssociate.size() > 0){
                outputMap.put('status', 'success');
                outputMap.put('caseAssociate', lstOfCaseAssociate);
            }

            System.debug('outputMap '+ outputMap.size());

        } catch (Exception e) {
            outputMap.put('status', 'error');
            throw new AuraHandledException(e.getMessage());
        }

        return JSON.serialize(outputMap);
    }
}