force-app/main/default/objects/Case_Associate__c/Case_Associate__c.object-meta.xml
<CustomObject>
    <label>Case Association</label>
    <nameField>
        <displayFormat>{000}</displayFormat>
        <label>Case Associate No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Associations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Case_Associate__c/fields/Associate_Type__c.field-meta.xml
<CustomField>
    <fullName>Associate_Type__c</fullName>
    <label>Associate Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Primary</fullName>
            </value>
            <value>
                <fullName>Secondary</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case_Associate__c/fields/Case_Number__c.field-meta.xml
<CustomField>
    <fullName>Case_Number__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case Number</label>
    <referenceTo>Case</referenceTo>
    <relationshipName>Case_Associates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case_Associate__c/fields/Entity1__c.field-meta.xml
<CustomField>
    <fullName>Entity1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Entity</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Entity_Type__c</field>
            <operation>equals</operation>
            <valueField>Account.Entity_Type__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipName>Case_Associates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/createPrimaryCaseAssociate.cls
public inherited sharing class createPrimaryCaseAssociate {
    public static void createPrimaryCaseAssociateRecord(List<Case> triggerNewCaseRecords, Map<Id,Case> triggerOldMapCaseRecords) {
        List<Case_Associate__c> caseAss = new List<Case_Associate__c>();
        Map<Id, Id> caseIdToEntityId = new Map<Id, Id>();
        Set<Id> conId = new Set<Id>();
        Map<Id, Contact> contactIdToCont;

        for(Case ics : triggerNewCaseRecords){
            if(ics.ContactId != null && triggerOldMapCaseRecords.size() <= 0){
                caseIdToEntityId.put(ics.Id, ics.ContactId );
                conId.add(ics.ContactId);
            }else if(triggerOldMapCaseRecords.size() > 0 && 
                triggerOldMapCaseRecords.get(ics.Id).ContactId != ics.ContactId){
                    caseIdToEntityId.put(ics.Id, ics.ContactId);
                    conId.add(ics.ContactId);
                }
        }

        if(conId.size() > 0){
            contactIdToCont = new Map<Id, Contact>([Select Id, AccountId from Contact Where Id IN: conId]);
        }

        if(caseIdToEntityId.size() > 0){
            for(Case_Associate__c caseAssociate : [SELECT Id, Case_Number__c, Entity1__c FROM Case_Associate__c
                WHERE Case_Number__c IN: caseIdToEntityId.keySet() AND 
                Associate_Type__c = 'Primary']){
                if(caseIdToEntityId.containsKey(caseAssociate.Case_Number__c)){
                    if(caseIdToEntityId.get(caseAssociate.Case_Number__c) != caseAssociate.Entity1__c){
                        //caseAssociate.Entity1__c = ;
                    }
                }
            }
        }
    }
}