force-app/main/default/objects/Case_Activity__c/Case_Activity__c.object-meta.xml
<CustomObject>
    <label>Case Activity</label>
    <nameField>
        <label>Case Activity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Activities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Case_Activity__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Case Activities</relationshipLabel>
    <relationshipName>Case_Activities</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Case_Activity__c/fields/IsEnabled__c.field-meta.xml
<CustomField>
    <fullName>IsEnabled__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsEnabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/EditActivityRedirectController.cls
public class EditActivityRedirectController {

    public Case_Activity__c activity {get; set;}
    
    public EditActivityRedirectController(ApexPages.StandardController controller) {activity = (Case_Activity__c)controller.getRecord();activity = [select id,IsEnabled__c,createdDate,case__r.type from Case_Activity__c where id=:activity.Id];
    }
    
    public pageReference setRedirect(){
        Datetime tym=Date.newInstance(2018,6,27);if(activity != null && activity.isEnabled__c==false && activity.createdDate > tym && activity.case__r.type=='Provider Audit New'){ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,'You cannot start working this activity until the pending actions taken on other activities.'));return null;}pageReference p=new pageReference('/'+activity.id+'/e?nooverride=1&retURL=/'+activity.id);p.setRedirect(true);return p;
    }

}