force-app/main/default/objects/Activity_Master__c/Activity_Master__c.object-meta.xml
<CustomObject>
    <label>Activity Master</label>
    <nameField>
        <label>Activity Master Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Activity Masters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Case/fields/Case_Name__c.field-meta.xml
<CustomField>
    <fullName>Case_Name__c</fullName>
    <label>Case Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case_Activity__c/Case_Activity__c.object-meta.xml
<CustomObject>
    <label>Case Activity</label>
    <nameField>
        <label>Case Activity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Activities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Case_Activity__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Case Activities</relationshipLabel>
    <relationshipName>Case_Activities</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/redirectToSampleActivityController.cls
public class redirectToSampleActivityController {
    
    public Case_Activity__c casActivity;
    public Activity_Master__c activityMaster;
    RecordType r;
    Case c;
    
    public redirectToSampleActivityController(ApexPages.StandardController controller) {
        activityMaster=(Activity_Master__c)controller.getRecord();
        activityMaster=[SELECT Id,Name from Activity_Master__c where Id=:activityMaster.Id];
        r=[SELECT Id,name,isActive,SobjectType from RecordType where name=:activityMaster.Name and isActive=true AND SobjectType='Case_Activity__c'];
        
        try{
            c=[SELECT id from Case where Case_Name__c='Sample Case'];
            casActivity=[SELECT Id,Case__c from Case_Activity__c where Case__r.Case_Name__c='Sample Case' AND RecordType.name=:activityMaster.Name];
        }
        Catch(Exception e){
            
        }
    }
    
    public pageReference reDirectToActivity(){
        if((casActivity == null || casActivity.Id == null) && r != null && c != null){                        
            casActivity=new Case_Activity__c(name=activityMaster.Name,RecordTypeId=r.Id,Case__c=c.Id);
            insert   casActivity;             
        }
            
        pageReference p;
        
        if(casActivity != null && casActivity.Id != null){
            p=new pageReference('/'+casActivity.Id);
        }
        else{
            p=new pageReference('/'+activityMaster.Id);
        }
        
        return p;        
    }

}