force-app/main/default/objects/Activity_Master__c/Activity_Master__c.object-meta.xml
<CustomObject>
    <label>Activity Master</label>
    <nameField>
        <label>Activity Master Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Activity Masters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Case/fields/Case_Name__c.field-meta.xml
<CustomField>
    <fullName>Case_Name__c</fullName>
    <label>Case Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Program_Name__c.field-meta.xml
<CustomField>
    <fullName>Program_Name__c</fullName>
    <label>Program Name New</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case_Activity__c/Case_Activity__c.object-meta.xml
<CustomObject>
    <label>Case Activity</label>
    <nameField>
        <label>Case Activity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Activities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Case_Activity__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>In-Progress</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/redirectToSampleActivityControllerTest.cls
@isTest(seeAlldata=true)
private class redirectToSampleActivityControllerTest{
    
    private testmethod static void redirectToSampleActivityControllerTest(){
        refreshActivityMaster.refreshActivityList();
        
        Activity_Master__c  act=[SELECT Id,Name from Activity_Master__c limit 1];
        
        Test.setCurrentpage(Page.redirectToSampleActivity);
        Apexpages.StandardController s=new Apexpages.StandardController(act);
        redirectToSampleActivityController re=new redirectToSampleActivityController(s);
        re.reDirectToActivity();
    }
    
    private testmethod static void redirectToSampleActivityControllerTest1(){
        refreshActivityMaster.refreshActivityList();
        
        Activity_Master__c  act=[SELECT Id,Name from Activity_Master__c limit 1];
        Case c=new Case(Case_name__c='Sample Case',Program_Name__c='Test');
        insert c;
        
        Test.setCurrentpage(Page.redirectToSampleActivity);
        Apexpages.StandardController s=new Apexpages.StandardController(act);
        redirectToSampleActivityController re=new redirectToSampleActivityController(s);
        re.reDirectToActivity();
    }
    
    private testmethod static void EditActivityRedirectControllerTest(){
        Case_Activity__c ac=[select id from Case_Activity__c order by createddate desc limit 1];
        
        Test.setCurrentpage(Page.EditActivityRedirect);
        Apexpages.StandardController s=new Apexpages.StandardController(ac);
        EditActivityRedirectController re=new EditActivityRedirectController(s);
        re.setRedirect();
        try{
        ac.status__c='Completed';
        update ac;
        }
        Catch(Exception e){
        
        }
    }
}