force-app/main/default/objects/Account/fields/Entity_Type__c.field-meta.xml
<CustomField>
    <fullName>Entity_Type__c</fullName>
    <label>Entity Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Billing Provider</fullName>
            </value>
            <value>
                <fullName>Rendering Provider</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Claims</fullName>
                <isActive>false</isActive>
                <label>Claims</label>
            </value>
            <value>
                <fullName>Member</fullName>
                <isActive>false</isActive>
                <label>Member</label>
            </value>
            <value>
                <fullName>Provider</fullName>
                <isActive>false</isActive>
                <label>Provider</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Case_Name__c.field-meta.xml
<CustomField>
    <fullName>Case_Name__c</fullName>
    <label>Case Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/No_Of_Installment__c.field-meta.xml
<CustomField>
    <fullName>No_Of_Installment__c</fullName>
    <label>No Of Installment</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Case/fields/Payment_Plan__c.field-meta.xml
<CustomField>
    <fullName>Payment_Plan__c</fullName>
    <label>Payment Plan</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/PP_Begin_Date__c.field-meta.xml
<CustomField>
    <fullName>PP_Begin_Date__c</fullName>
    <label>PP Begin Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/PP_Type__c.field-meta.xml
<CustomField>
    <fullName>PP_Type__c</fullName>
    <label>PP Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>One Time</fullName>
            </value>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Yearly</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Total_PP_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_PP_Amount__c</fullName>
    <label>Total PP Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Case_Associate__c/Case_Associate__c.object-meta.xml
<CustomObject>
    <label>Case Association</label>
    <nameField>
        <displayFormat>{000}</displayFormat>
        <label>Case Associate No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Associations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Case_Associate__c/fields/Associate_Type__c.field-meta.xml
<CustomField>
    <fullName>Associate_Type__c</fullName>
    <label>Associate Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Primary</fullName>
            </value>
            <value>
                <fullName>Secondary</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case_Associate__c/fields/Case_Number__c.field-meta.xml
<CustomField>
    <fullName>Case_Number__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case Number</label>
    <referenceTo>Case</referenceTo>
    <relationshipName>Case_Associates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case_Associate__c/fields/Entity1__c.field-meta.xml
<CustomField>
    <fullName>Entity1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Entity</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Entity_Type__c</field>
            <operation>equals</operation>
            <valueField>Account.Entity_Type__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipName>Case_Associates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case_Associate__c/fields/Entity_Type__c.field-meta.xml
<CustomField>
    <fullName>Entity_Type__c</fullName>
    <label>Case Associate</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Provider</fullName>
            </value>
            <value>
                <fullName>Member</fullName>
            </value>
            <value>
                <fullName>Claims</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case_Associate__c/recordTypes/Billing_Provider.recordType-meta.xml
<RecordType>
    <fullName>Billing_Provider</fullName>
    <active>true</active>
    <label>Billing Provider</label>
</RecordType>

force-app/main/default/objects/Case_Associate__c/recordTypes/Provider.recordType-meta.xml
<RecordType>
    <fullName>Provider</fullName>
    <active>true</active>
    <label>Provider</label>
</RecordType>

force-app/main/default/classes/associatedCaseListTest.cls
@isTest
public with sharing class associatedCaseListTest {
    @isTest
    static void associatedCaseListTest() {
        Id billingProviderRecordtypeId =  Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Billing_Provider').getRecordTypeId();

        Account acc1 = new Account(
            FirstName = 'Test',
            LastName = 'Test 1',
            recordtypeId = billingProviderRecordtypeId,
            Entity_Type__c = 'Billing Provider'
        );
        insert acc1;

        Account acc2 = new Account(
            FirstName = 'Test',
            LastName = 'Test 2',
            recordtypeId = billingProviderRecordtypeId,
            Entity_Type__c = 'Billing Provider'
        );
        insert acc2;

        Case csWeekly1 = new Case(
            Case_Name__c = 'Test Case 1',
            No_Of_Installment__c = 2,
            PP_Begin_Date__c = system.today(),
            Payment_Plan__c = 'Yes',
            PP_Type__c = 'Monthly',
            Total_PP_Amount__c = 15000
        );
        insert csWeekly1;

        Case csWeekly2 = new Case(
            Case_Name__c = 'Test Case 2',
            No_Of_Installment__c = 2,
            PP_Begin_Date__c = system.today(),
            Payment_Plan__c = 'Yes',
            PP_Type__c = 'Monthly',
            Total_PP_Amount__c = 15000
        );
        insert csWeekly2;

        Case_Associate__c caseAssociate1 = new Case_Associate__c(
            Entity1__c = acc1.Id,
            Case_Number__c = csWeekly1.Id,
            Associate_Type__c = 'Primary',
            Entity_Type__c = 'Billing Provider'
        );

        Case_Associate__c caseAssociate2 = new Case_Associate__c(
            Entity1__c = acc2.Id,
            Case_Number__c = csWeekly1.Id,
            Associate_Type__c = 'Secondary',
            Entity_Type__c = 'Billing Provider'
        );

        Case_Associate__c caseAssociate3 = new Case_Associate__c(
            Entity1__c = acc1.Id,
            Case_Number__c = csWeekly2.Id,
            Associate_Type__c = 'Primary',
            Entity_Type__c = 'Billing Provider'
        );

        Case_Associate__c caseAssociate4 = new Case_Associate__c(
            Entity1__c = acc2.Id,
            Case_Number__c = csWeekly2.Id,
            Associate_Type__c = 'Secondary',
            Entity_Type__c = 'Billing Provider'
        );

        List<Case_Associate__c> caseAssociateList = new List<Case_Associate__c>{caseAssociate1, caseAssociate2, caseAssociate3, caseAssociate4};
        insert caseAssociateList;

        String outputMapStr = associatedCaseList.fetchCaseListAssociated(csWeekly1.Id);
        
        System.debug(' outputMapStr -> ' +outputMapStr);
    }
}