force-app/main/default/objects/Account/fields/Entity_Type__c.field-meta.xml
<CustomField>
    <fullName>Entity_Type__c</fullName>
    <label>Entity Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Billing Provider</fullName>
            </value>
            <value>
                <fullName>Rendering Provider</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Claims</fullName>
                <isActive>false</isActive>
                <label>Claims</label>
            </value>
            <value>
                <fullName>Member</fullName>
                <isActive>false</isActive>
                <label>Member</label>
            </value>
            <value>
                <fullName>Provider</fullName>
                <isActive>false</isActive>
                <label>Provider</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case_Associate__c/Case_Associate__c.object-meta.xml
<CustomObject>
    <label>Case Association</label>
    <nameField>
        <displayFormat>{000}</displayFormat>
        <label>Case Associate No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Associations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Case_Associate__c/fields/Associate_Type__c.field-meta.xml
<CustomField>
    <fullName>Associate_Type__c</fullName>
    <label>Associate Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Primary</fullName>
            </value>
            <value>
                <fullName>Secondary</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case_Associate__c/fields/Case_Number__c.field-meta.xml
<CustomField>
    <fullName>Case_Number__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case Number</label>
    <referenceTo>Case</referenceTo>
    <relationshipName>Case_Associates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case_Associate__c/fields/Entity1__c.field-meta.xml
<CustomField>
    <fullName>Entity1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Entity</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Entity_Type__c</field>
            <operation>equals</operation>
            <valueField>Account.Entity_Type__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipName>Case_Associates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case_Associate__c/fields/Entity_Type__c.field-meta.xml
<CustomField>
    <fullName>Entity_Type__c</fullName>
    <label>Case Associate</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Provider</fullName>
            </value>
            <value>
                <fullName>Member</fullName>
            </value>
            <value>
                <fullName>Claims</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CaseAssociationsController.cls
public class CaseAssociationsController {
    
    public List<Case_Associate__c> caList {get; set;}
    public Account a;
    public string NewCaseUrl {get; set;}
    
    public CaseAssociationsController(ApexPages.StandardController controller) {
        a=(Account)controller.getRecord();
        caList=[Select Name, Entity1__c, Case_Number__r.Account.Name, Case_Number__r.AccountId, Case_Number__c,
                Case_Number__r.CaseNumber, Case_Number__r.Subject, Case_Number__r.Priority, Case_Number__r.Status,
                Case_Number__r.Owner.Name, Case_Number__r.OwnerId, Case_Number__r.CreatedDate, Case_Number__r.ClosedDate, 
                Case_Number__r.Type, Entity_Type__c, Associate_Type__c 
                FROM Case_Associate__c where Entity1__c=:a.Id Order By CreatedDate];
        NewCaseUrl = URL.getSalesforceBaseUrl().toExternalForm()+'/500/e?def_account_id='+a.Id+'&retURL=/'+a.Id;
    }
    
    public static void createRecord(list<case> caseRec){
        list<Case_Associate__c> CAlist= new list<Case_Associate__c>();
        Case_Associate__c curCA = new Case_Associate__c();
        //list<case> accList= new list<case>([select id,accountid from case where id in:caseRec]);
        list<id> accIds= new list<id>();
        for(case a:caseRec){
            accIds.add(a.accountId);
        }
        map<id,account> acctoRecordTypeMap = new map<id,account>([select id,recordtype.id,recordtype.name from account where id in :accIds]);
        list<RecordType> associationRecordType= new list<RecordType>();
        map<string,id> rmap = new map<String,id>();
        for(RecordType r:[SELECT Name,id FROM RecordType WHERE SobjectType='Case_Associate__c']){
            rmap.put(r.name,r.id);
        }
        
        if(caseRec.size()>0 && caseRec !=null){
            for(case currentCase:caseRec){
                if(currentCase.AccountId != null && rmap.containskey(acctoRecordTypeMap.get(currentCase.AccountId).recordType.name)){
                    curCA.Case_Number__c=currentCase.id;
                    curCA.Associate_Type__c='Primary';
                    curCA.RecordTypeId=(id)rmap.get(acctoRecordTypeMap.get(currentCase.AccountId).recordType.name);
                    curCA.Entity1__c=currentCase.AccountId;
                    CURca.Entity_Type__c=acctoRecordTypeMap.get(currentCase.AccountId).recordType.Name;
                    CAlist.add(curCA);
                    System.debug('Case Association record added to list' +CAlist.size());
                }
            }
            insert CAlist;
            system.debug('Records created' +CAlist.size());
        }
        
    }
}