force-app/main/default/objects/Account/fields/Entity_Type__c.field-meta.xml
<CustomField>
    <fullName>Entity_Type__c</fullName>
    <label>Entity Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Billing Provider</fullName>
            </value>
            <value>
                <fullName>Rendering Provider</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Claims</fullName>
                <isActive>false</isActive>
                <label>Claims</label>
            </value>
            <value>
                <fullName>Member</fullName>
                <isActive>false</isActive>
                <label>Member</label>
            </value>
            <value>
                <fullName>Provider</fullName>
                <isActive>false</isActive>
                <label>Provider</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Case_Name__c.field-meta.xml
<CustomField>
    <fullName>Case_Name__c</fullName>
    <label>Case Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case_Associate__c/Case_Associate__c.object-meta.xml
<CustomObject>
    <label>Case Association</label>
    <nameField>
        <displayFormat>{000}</displayFormat>
        <label>Case Associate No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Associations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Case_Associate__c/fields/Associate_Type__c.field-meta.xml
<CustomField>
    <fullName>Associate_Type__c</fullName>
    <label>Associate Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Primary</fullName>
            </value>
            <value>
                <fullName>Secondary</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case_Associate__c/fields/Case_Number__c.field-meta.xml
<CustomField>
    <fullName>Case_Number__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case Number</label>
    <referenceTo>Case</referenceTo>
    <relationshipName>Case_Associates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case_Associate__c/fields/Entity1__c.field-meta.xml
<CustomField>
    <fullName>Entity1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Entity</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Entity_Type__c</field>
            <operation>equals</operation>
            <valueField>Account.Entity_Type__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipName>Case_Associates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case_Associate__c/fields/Entity_Type__c.field-meta.xml
<CustomField>
    <fullName>Entity_Type__c</fullName>
    <label>Case Associate</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Provider</fullName>
            </value>
            <value>
                <fullName>Member</fullName>
            </value>
            <value>
                <fullName>Claims</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case_Associate__c/recordTypes/Member.recordType-meta.xml
<RecordType>
    <fullName>Member</fullName>
    <active>false</active>
    <label>Member</label>
</RecordType>

force-app/main/default/classes/caseAssignment_Test.cls
/*
Created By : Orbit Team - Soundar
Date       : 11/10/2017 
For        : CaseAssignment
*/

@IsTest    
Public Class caseAssignment_Test{
    public Static testMethod void CaseAssociate(){
        
        RecordType r = [select id,Name from RecordType where SobjectType='Account' and Name='Member'];
        Account a=new Account(lastname='Test Account',RecordtypeId=r.Id);
        insert a;
         
        //Insert record Type
        RecordType rec = New RecordType();
        rec.name = 'Claim';
        
        //Inser Case
        Case cs = new Case();
        cs.Case_Name__c = 'Test Case';
        //cs.RecordType = rec.Id;
        cs.accountid=a.id;
        insert cs;
        
        RecordType rt = [select id,Name from RecordType where SobjectType='Case_Associate__c' and Name='Member' Limit 1];
        
        /*Schema.DescribeSObjectResult cfrSchema = Schema.SObjectType.Account; 
Map<String,Schema.RecordTypeInfo> CaseAssociateRecType = cfrSchema.getRecordTypeInfosByName(); 
Id rtId = CaseAssociateRecType .get('Claim').getRecordTypeId();*/
   
        //Insret Case Associate
        Case_Associate__c ca = New Case_Associate__c();
        ca.Associate_Type__c = 'Primary';
        ca.Case_Number__c = cs.Id;
        ca.Entity1__c=a.id;
        ca.Entity_type__c='Member';
        ca.recordTypeId = rt.Id;
        
        System.debug('@@@@@@@@ record Type | ' + ca.recordTypeId);
        //ca.recordtypeid = CaseAssociateRecType .get('Claim').getRecordTypeId();
        insert ca;
        ca.Associate_Type__c = 'Secondary';
        update ca;
        
        ApexPages.StandardController sc = new ApexPages.StandardController(ca);
        caseAssignment cas = New caseAssignment(sc);
        cas.test();
        cas.GetRecordTypes();
        cas.updateRecordType();
        cas.Cancel();
        
        sc= new ApexPages.StandardController(a);
        CaseAssociationsController caseAssociation=new CaseAssociationsController(sc);
        
    }
}